spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    # mysql username & password
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
